baseURL = "https://scalacenter.github.io/bloop"
languageCode = "en-us"
title = "Bloop"
theme = "kube"
description = ""
enableEmoji = true
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Scala Center"
  github = "scalacenter" # add your github profile name
  twitter = "scala_lang"
  email = "jorgevc@fastmail.es"
  githubURL = "https://github.com/scalacenter/bloop"
  license = "Apache2"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
[[menu.extra]]
    name = "View on GitHub"
    url = "https://github.com/scalacenter/bloop"
